name: invoice
description: "Application for sales management"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

#------------------ PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages

  # Icons
  cupertino_icons: ^1.0.8

  # State Management

  # Product Specific

#------------------ ./PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

#------------------ LOCAL ASSETS ------------------#
assets:
  - assets/logos/
  - assets/images/
  - assets/icons/

#------------------ LOCAL FONTS ------------------#
 

  
  
  
  
  
  
  
